Repository vmck/acs-interface, pull requests merged in 2020-10, with the labels that each got.

#260 Resize img and change with png
  interface/templates/interface/generics/navbar.html
  interface/templates/interface/media/vmck.png
  interface/templates/interface/media/vmck.svg
Labels: bug, student

#262 Select backend
  interface/backend/submission/evaluator/vmck.py
  interface/settings.py
Labels: enhancement

#267 Add CONTRIB.md
  CONTRIB.md
Labels: coding style

#268 Recomputes total score when the soft deadline changes
  interface/admin.py
  interface/models.py
  testsuite/conftest.py
  testsuite/test_student_workflow.py
  testsuite/test_ta_workflow.py
Labels: enhancement, teaching assistant

#270 New state ERROR for submission update method
  CONTRIB.md
  interface/backend/submission/evaluator/vmck.py
  interface/models.py
  testsuite/test_internals.py
Labels: hacktoberfest-accepted

#281 Update README
  Readme.md
Labels: bug

#284 Profiler
  .drone.yml
  .github/workflows/ci.yml
  .github/workflows/linter.yml
  Pipfile
  Pipfile.lock
  Readme.md
  Vagrantfile
  ci/code-coverage.sh
  ci/provision-acs-interface.sh
  ci/provision-cluster.sh
  ci/provision-system.sh
  ci/provision-vmck.sh
  ci/test-pytest.sh
  examples/.env
  examples/minio.sh
  examples/postgres.sh
  interface/settings.py
  interface/templates/interface/submission_list.html
  interface/templates/interface/subs_for_user.html
  interface/templates/interface/user_page.html
  interface/templates/interface/users_list.html
  interface/urls.py
  interface/views.py
  pyproject.toml
  runinterface
  test.sh
  testsuite/test_student_workflow.py
  testsuite/test_views.py
Labels: enhancement

#255 Add unify config
  ci/fixtures.json
  interface/backend/submission/evaluator/vmck.py
  interface/migrations/0023_auto_20201022_1258.py
  interface/migrations/0023_auto_20201024_1949.py
  interface/migrations/0024_auto_20201024_1632.py
  interface/models.py
  interface/scoring.py
  interface/utils.py
  pyproject.toml
  testsuite/conftest.py
  testsuite/test_student_workflow.py
  testsuite/test_ta_workflow.py
Labels: enhancement, teaching assistant
